# Generated by Django 5.1.7 on 2025-03-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='myapp.album')),
            ],
        ),
    ]
