# Generated by Django 5.1.7 on 2025-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_albumcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AlbumCover',
        ),
    ]
