# Generated by Django 5.1.7 on 2025-03-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_album_cover_url_delete_albumcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
