# Generated by Django 5.1.7 on 2025-03-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_band_band_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band_description',
            new_name='description',
        ),
    ]
