# Generated by Django 5.1.6 on 2025-02-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze_punku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze_punku.band'),
        ),
    ]
